### ISSUE TITLE
License

### ISSUE THREAD

**Issue by raucao** [67P/ipfs-cookbook#1]
Is there a specific reason for releasing this under the Apache license? I don't see benefits for Kosmos, but it does make contributing harder, because we'd need to have contributors sign a CLA in order to be flexible with how we use and distribute this codebase in the future.

Also, as there's no legal entity by the name of Kosmos, I think we have to change the name there. In other places we use "Kosmos Developers" and link the words to some GitHub contribution page. But now we can actually link it to https://kredits.kosmos.org as the decentralization gods intended. :)

**Comment by gregkare** [comment]
Good point, I actually wanted to open an issue about picking the license. MIT would make more sense for a cookbook like this, right?

**Comment by raucao** [comment]
Yes. Anything that's a simple disclaimer for liability and grants permission to do whatever someone wants with it.
